from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field
from typing import List
from src.graph.llm import llm

class GenerateAnswer(BaseModel):
    '''
    Class for defining the generated answer
    Attributes:
        answer: The answer generated by LLM for the suer question based on the retrieved documents
    '''
    answer: str = Field(...,
                        description="The answer generated by LLM for the user question based on the retrieved documents")


prompt = '''You are a helpful Question Answering assistant. Use the following retrieved documents to generate a comprehensive answer for the question.
Make sure to use all the relevant information from the retrieved documents to generate the answer.If the answer cannot be found in the retrieved documents, say you don't know. Always use all the relevant information from the retrieved documents to generate the answer.
Question: {question}
Retrieved Documents: {documents}
Answer: '''

prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", prompt)
    ]
    )
generate_chain = prompt_template | llm.with_structured_output(GenerateAnswer)

if __name__ == "__main__":
    # Example usage
    response = generate_chain.invoke(
        {
            "question": "What is Langgraph?", 
            "documents": [
                "Pixel 6 is the latest smartphone from Google, released in October 2021. It features a 6.4-inch OLED display, a powerful Tensor chip, and an advanced camera system. The Pixel 6 runs on Android 12 and offers a smooth and responsive user experience.",
                "Langgraph is a knowledge graph that represents the relationships between different concepts and entities in a structured format. It is designed to help machines understand and reason about the world by organizing information in a way that is easy to query and analyze. Langgraph can be used for various applications, including natural language processing, information retrieval, and data integration.",
                "Pizza is a popular Italian dish that consists of a round, flat base of dough topped with various ingredients such as tomato sauce, cheese, and toppings like pepperoni, mushrooms, and olives. It is typically baked in an oven and can be served in different styles, including thin crust, deep dish, and stuffed crust. Pizza is enjoyed by people all around the world and is often considered a comfort food."
            ]
        }
    )
    print(response.answer)
        